// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukxgmshlnqzkesyrtbyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVreGdtc2hsbnF6a2VzeXJ0YnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTMxNTQsImV4cCI6MjA3MTcyOTE1NH0.8rGVCdDeYeNX7KXf3g_vy1vGraCu7rsj8t789Rpm2LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});